export type Label =
  | "EVM Transaction"
  | "Farming deposit"
  | "Farming withdraw"
  | "Liquidity removed"
  | "Liquidity added"
  | "Swap"
  | "Existential deposit paid" // only used for events of name 'ExistentialDepositPaid'
  | "Crowdloan contribution"
  | "Liquid staking token minted"
  | "Liquid staking token rebonded"
  | "Liquid staking token redeemed"
  | "Liquid staking token redeem success"
  | "XCM transfer"
  | "Treasury grant"
  | "Reward"
  | "Staking reward"
  | "Staking slashed"
  | "Coretime purchase"
  | "Migrated delegation"
  | "Stake"
  | "Fee"
  | "Unstake"
  | "CEX transfer" // Used for any transer to or from a centralized exchange
  | "Account created"
  | "Reserve repatriated"
  | "DEX fee"
  | "Interest payment"
  | "Transfer"; // transfer of an asset which doesn't fall in any of the other categories
