export type Label =
  | "EVM Transaction"
  | "Farming deposit"
  | "Farming withdraw"
  | "Liquidity removed"
  | "Liquidity added"
  | "Swap"
  | "Crowdloan contribution"
  | "Liquid staking token minted"
  | "Liquid staking token redeemed"
  | "XCM transfer"
  | "Treasury grant"
  | "Reward"
  | "Staking reward"
  | "Staking slashed"
  | "Coretime purchase"
  | "Remove from Pool"
  | "Migrated delegation"
  | "Reserve repatriated";
