name: Build and Test

on:
  push:
    branches:
      - '**'  
  pull_request:
    branches:
      - '**'  

jobs:
  server-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Server Dependencies
        working-directory: server
        run: npm install

      - name: Run Server Unit Tests
        working-directory: server
        run: npm run test

      - name: Run Server Integration Tests
        working-directory: server
        run: npm run integration-tests

  client-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: client
        run: npm ci

      - name: Run Client Unit Tests
        working-directory: client
        run: npm run test

      - name: Install Playwright Browsers
        working-directory: client
        run: npx playwright install chromium --with-deps

      - name: Run Browser tests
        working-directory: client
        run: npm run integration-tests 
